name: Xcode - Build and Analyze

on: workflow_dispatch
  #push:
   # branches: [ "master" ]
 # pull_request:
  #  branches: [ "master" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run:  chmod +x ./mediapipe/objc/mediapipe_framework_ios_build.sh
      - name: Run
        run:  ./mediapipe/objc/mediapipe_framework_ios_build.sh

      - uses: actions/upload-artifact@v3
        with:
         name: libmediapipe_framework_ios
         path: bazel-bin/mediapipe/objc/libmediapipe_framework_ios.a
        
